"""alert webhook config

Revision ID: 2c5c3c6eeac9
Revises: 86363ee90534
Create Date: 2026-06-16 08:58:05.266282

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2c5c3c6eeac9'
down_revision: Union[str, None] = '86363ee90534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_webhooks',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_webhooks_workspace_id'), 'alert_webhooks', ['workspace_id'], unique=True)
    # (autogenerate also wanted to drop unrelated ix_paper_workspace_status /
    # ix_watchlist_workspace — left in place, not part of this change.)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_webhooks_workspace_id'), table_name='alert_webhooks')
    op.drop_table('alert_webhooks')
    # ### end Alembic commands ###
