"""desk per-role llm config

Revision ID: 86363ee90534
Revises: dc61eaf141c8
Create Date: 2026-06-15 23:57:54.313818

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '86363ee90534'
down_revision: Union[str, None] = 'dc61eaf141c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desk_llm_configs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desk_llm_configs_workspace_id'), 'desk_llm_configs', ['workspace_id'], unique=True)
    # (autogenerate also wanted to drop unrelated ix_paper_workspace_status /
    # ix_watchlist_workspace — left in place, not part of this change.)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_desk_llm_configs_workspace_id'), table_name='desk_llm_configs')
    op.drop_table('desk_llm_configs')
    # ### end Alembic commands ###
