"""trading desk snapshots + persistent alerts

Revision ID: dc61eaf141c8
Revises: e3a5b7c9d1f2
Create Date: 2026-06-15 22:30:19.975749

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'dc61eaf141c8'
down_revision: Union[str, None] = 'e3a5b7c9d1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desk_snapshots',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('characters', sa.JSON(), nullable=False),
    sa.Column('prev_signals', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('priced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desk_snapshots_workspace_id'), 'desk_snapshots', ['workspace_id'], unique=True)
    op.create_table('trading_alerts',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('strategy', sa.String(length=40), nullable=True),
    sa.Column('timeframe', sa.String(length=8), nullable=True),
    sa.Column('win_chance_pct', sa.Float(), nullable=True),
    sa.Column('label', sa.String(length=40), nullable=True),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_alerts_workspace_id'), 'trading_alerts', ['workspace_id'], unique=False)
    # NOTE: autogenerate also wanted to drop ix_paper_workspace_status /
    # ix_watchlist_workspace (they exist in the DB but not in model metadata).
    # Those are unrelated to this change — leave them in place.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_alerts_workspace_id'), table_name='trading_alerts')
    op.drop_table('trading_alerts')
    op.drop_index(op.f('ix_desk_snapshots_workspace_id'), table_name='desk_snapshots')
    op.drop_table('desk_snapshots')
    # ### end Alembic commands ###
